extends: ../../train/joint.yaml
name: graduation_bear_joint

args:
  instance_data_root: ./datasets/3d-custombench/subjects/graduation_bear/images
  reference_path: ./datasets/3d-custombench/subjects/graduation_bear/references
  output_dir: ./outputs/joint/graduation_bear
  train_prompts:
    - A video of a [rhs plushie].
  validation_prompts:
    - A video of a [rhs plushie] perched atop a bookshelf in a cozy living room, next to old books and a framed family photo.
